---
title: "Renewvia - Survey Impact Analysis"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

# Importing libraries

```{r}
# tinytex::install_tinytex()
library(dataMaid) 
library(ggplot2)
library(dplyr)
library(lessR)
library(tidyr)
library(ggpubr)
library(exact2x2)
library(stringr)
```

# Loading the data

```{r}
## Locading the cleaned data sets
# Intial Survey
initial_clean <- read.csv("data_cleaning/datasets_clean/initial_clean.csv")
head(initial_clean)
```

```{r}
# Household Post-Survey
hs_post_clean <- read.csv("data_cleaning/datasets_clean/hs_post_clean.csv")
head(hs_post_clean)
```

```{r}
# Commercial & Insitution Post-Survey
ci_post_clean <- read.csv("data_cleaning/datasets_clean/ci_post_clean.csv")
head(ci_post_clean)
```

# 1- Demographics

```{r}
# Age & Gender
par(mfrow = c(1, 2))
hs_pre <- initial_clean %>%
                    filter(status == "pre_connection")

# Transforming the vvariables
hs_pre$age <- as.numeric(hs_pre$age) 
hs_pre$gender <- as.factor(hs_pre$gender)

# Age
age_hist <- ggplot(hs_pre %>% filter(age < 100), aes(x=age)) + 
              geom_histogram(color="black", fill="white") # Save histogram data


# Pie Chart
# Data transformation
pie_data <- hs_pre %>% 
            group_by(gender) %>% # Variable to be transformed
            count() %>% 
            ungroup() %>% 
            mutate(perc = n / sum(n)) %>% 
            arrange(perc) %>%
            mutate(labels = scales::percent(perc))

gender_pie <- ggplot(pie_data, aes(x = "", y = perc, fill = gender)) +
                  geom_col() +
                  geom_text(aes(label = labels),
                            # position = position_stack(vjust = 0.5)
                            ) +
                  coord_polar(theta = "y")

ggarrange(age_hist, gender_pie,
          labels = c("Age", "Gender"),
          ncol = 2, nrow = 1)
```
